#!/bin/bash

formatted_test() {
  command=$1
  check_regex=$2
  test_file=$3

  test_dir="$(cd `dirname $test_file` && pwd)"
  lib_dir="$(cd `dirname $test_dir`/lib && pwd)"

  if [ "$VERBOSE" = "1" ]; then
    $command -I$lib_dir -I$test_dir $test_file
    return $?
  fi

  syntax_check=`ruby -c "$test_file" 2>&1`
  if [ "$syntax_check" = "Syntax OK" ]; then
    output="$($command -I$lib_dir -I$test_dir $test_file 2>&1)"
    failed=$?
    if echo "$output" | grep "^Finished" &>/dev/null; then
      echo "$output"
      exit $failed
    else
    # possibly a problem with the test file (e.g. NameError)
cat <<EOF

  1) Error:
`echo "$output" | head -1 | cut -d: -f3-`
`echo "$output" | sed -e 's|^|    |g'`

EOF
    fi
  else
    cat <<EOF
  1) Error:
`echo $syntax_check | cut -d: -f3`
`echo "$syntax_check" | sed -e 's|^|    |g'`

EOF
    exit 1
  fi
}
